version: '3'

services:
  frontend:
    build: ./frontend 
    ports:
      - "3000:3000"
    container_name: frontend-docker
    restart: always
    links:
      - backend 
  backend: 
    build: ./backend
    ports:
      - "3001:3001"
    container_name: backend-docker
    restart: always